### ISSUE TITLE
Randomize the pictures every 2 minutes??

### ISSUE THREAD

**Issue by MiguelCosme** [margemsulcrossfit/margemsulcrossfit#12]
Is it cool to add a function to randomize the pictures every two or so minutes?
Or is it too much?

**Comment by mariaines00** [comment]
too much.
Close #12

**Comment by MiguelCosme** [comment]
Noted @mariaines00 .

**Comment by mariaines00** [comment]
sorry, but imagine it. It's gonna be 'folclórico' and who wants that?
