### ISSUE TITLE
Add scroll to bot page.

### ISSUE THREAD

**Issue by margemsulcrossfit** [margemsulcrossfit/margemsulcrossfit#4]

**Comment by mariaines00** [comment]
should we add a link or a button for the scroll to get called or ?

**Comment by MiguelCosme** [comment]
I'd prefer a rounded square button on the right bottom corner with a down arrow inside.

**Comment by mariaines00** [comment]
I see. Sounds nice, but on mobiles might be too much no?

Also, couldn't the 'Mais Informacoes' link redirect you to that part with the contacts instead of the pictures?
Just a suggestion. But I also like the way it is now

:)

**Comment by MiguelCosme** [comment]
I agree with you, maybe we should change the text on that first button. And couldn't we make the button disappear on the mobile version?

**Comment by mariaines00** [comment]
sounds great

**Comment by mariaines00** [comment]
@MiguelCosme any progress on this?

**Comment by MiguelCosme** [comment]
No, been busy.

**Comment by mariaines00** [comment]
Same. I wanted to do it but I can't find the time for it tho.
